### ISSUE TITLE
qr code generator not working. Please Help!

### ISSUE THREAD

**Issue by hmjk99** [Gaylord-Julien/strapi-plugin-qrcode-generator#7]
Hello. I installed this plugin and did everything as the readme says but it is not working. i see it in my list of plugins but don't see it in my category content. I am using typescript and my strapi version is 4.8.2
<img width="379" alt="Screenshot 2024-03-26 at 7 19 17 PM" src="https://github.com/Gaylord-Julien/strapi-plugin-qrcode-generator/assets/124408498/0de8f2e0-12f9-4b24-b511-b10686a818f0">

**Comment by mariomurrent-softwaresolutions** [comment]
@hmjk99 How did you solve the isses?
I'm having the same problem that the QR code does not show up
